variable "vpcid" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "highcpu" {}
variable "lowcpu" {}
variable "ami" {}
variable "instance_type" {}
variable "public_key_path" {}
variable "userdata" {}
variable "env_name" {}
variable "app_port" {}
variable "health_path" {}
variable "vpc_id" {}
