version: 0.0
os: linux
files:
 - source: .
   destination: /home/ec2-user/app
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
   - location: scripts/delete_app
     timeout: 300
     runas: root
  AfterInstall:
   - location: scripts/install_app_dependencies
     timeout: 300
     runas: root
   - location: scripts/download_secrets
     timeout: 300
     runas: root
  ApplicationStart:
   - location: scripts/start_server
     timeout: 500
     runas: root