version: "3"
services:
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: registry.digitalocean.com/conquext/slbot:${CONQUEXT_BRANCH:-latest}
    restart: on-failure
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app
    env_file:
      - .env
    networks:
      - backend
  # redis:
  #   image: "redis"
  #   ports:
  #     - "6380:6379"
  # kafka:
  #   image: "landoop/fast-data-dev"
  #   environment:
  #     - ADV_HOST=127.0.0.1
  #   ports:
  #     - "2181:2181"
  #     - "3030:3030"
  #     - "8081:8081"
  #     - "8082:8082"
  #     - "9092:9092"

networks:
  backend: