#!/bin/bash
ENVFILE=/home/ec2-user/app/.env
DIR=/home/ec2-user/app/
#create config directory if not exists
mkdir $DIR -p
#get secrets files depending on current deployment environment
if [[ "$DEPLOYMENT_GROUP_NAME" == "Dev-"* ]];
then
#here we are assuming that the EC2 has a role for accessing the S3 bucket
sudo aws s3 cp s3://slboty/dev $DIR --recursive --exclude "*" --include "*.env"
elif [[ "$DEPLOYMENT_GROUP_NAME" == *"STAGING" ]];
then
#here we are assuming that the EC2 has a role for accessing the S3 bucket
sudo aws s3 cp s3://secrets-bucket/slboty/staging $DIR --recursive --exclude "*" --include "*.env"
elif [[ "$DEPLOYMENT_GROUP_NAME" == *"QA" ]];
then
sudo aws s3 cp s3://secrets-bucket/slboty/qa $DIR --recursive --exclude "*" --include "*.env"
elif [[ "$DEPLOYMENT_GROUP_NAME" == *"PROD" ]];
then
sudo aws s3 cp s3://secrets-bucket/slboty/prod $DIR --recursive --exclude "*" --include "*.env"
fi