#!/bin/bash
cd /home/ec2-user/app
yum update -y
yum install git wget ruby -y
yum install -y yum-utils device-mapper-persistent-data lvm2
yum-config-manager — add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install docker
yum install docker-compose