#!/bin/bash
cd /home/ec2-user/app
yum update -y
yum install git wget ruby -y
yum install -y yum-utils device-mapper-persistent-data lvm2
yum-config-manager — add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install docker -y
# yum install docker-compose -y

docker -v

sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)"  -o /usr/local/bin/docker-compose
sudo mv /usr/local/bin/docker-compose /usr/bin/docker-compose
sudo chmod +x /usr/bin/docker-compose

docker-compose -v